version: '3.6'

services:
  elasticsearch:
    container_name: elasticsearch
    image: amazon/opendistro-for-elasticsearch:1.13.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - network.host=0.0.0.0
    volumes:  
    -  ./opendistro/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9600:9600"

